### ISSUE TITLE
Can't load on linux

### ISSUE THREAD

**Issue by Cofresi** [nomic-io/node-merk#2]
I get the following error when loader.js tries to load the build on linux:

```
cofresi@marin:~/merk-test$ node index
internal/modules/cjs/loader.js:717
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/cofresi/merk-test/node_modules/merk/build/x86_64-unknown-linux-gnu.node: cannot allocate memory in static TLS block
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/cofresi/merk-test/node_modules/merk/lib/index.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
```

I tried on Ubuntu 18.04 bionic and on Linux Mint 19 and Arch 5.5.13.

It works fine on Mac though.

Maybe you can reproduce it?

**Comment by Cofresi** [comment]
I was able to get rid of this error by compiling a new linux binary adding the `disable_initial_exec_tls` feature to the jemallocator dependency in merk's Cargo.toml.
```
[dependencies.jemallocator]
version = "0.3.2"
features = ["disable_initial_exec_tls"]
```
https://github.com/Cofresi/merk/tree/fix-tls-error

More info about this here:
https://docs.rs/crate/jemalloc-sys/0.3.2
https://github.com/jemalloc/jemalloc/pull/1180/files

**Comment by keppel** [comment]
Thanks for debugging this! Should be resolved on the latest merk / node-merk now.
